#Next Image
FROM node:16.18.0 AS build

WORKDIR /app

#COPY package.json and package-lock.json
COPY client/package*.json ./

#Install dependencies
RUN npm install 

#COPY the rest of the application code
COPY client .

#COPY prisma directory
COPY prisma ./prisma

#Build the Next.js application
WORKDIR /app/prisma
RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]