#Next Image
FROM node:16.18.0 AS build

WORKDIR /app

#COPY package.json and package-lock.json
COPY package*.json ./

#Install dependencies
RUN npm install 

#COPY the rest of the application code
COPY . .

#Build the Next.js application
RUN npx prisma generate 

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]