version: 0.2

phases:
  build:
    commands:
      - echo '[{"name":"'${CONTAINER_NAME}'","imageUri":"'${REPOSITORY_NAME}:${IMAGE_TAG}'"}]' > backendimagedefinitions.json

artifacts:
  files:
    - backendimagedefinitions.json
