version: 0.2

phases:
  install:
    commands:
      - cd server
  build:
    commands:
      - echo '[{"name":"'${CONTAINER_NAME}'","imageUri":"'${REPOSITORY_NAME}:${IMAGE_TAG}'"}]' > backendimagedefinitions.json

artifacts:
  files:
<<<<<<< HEAD
    - server/appspec.json
    - server/backendimagedefinitions.json
=======
    - appspec.json
    - backendimagedefinitions.json
    - **/*
  base-directory: server/
>>>>>>> atomic
