#Express Image
FROM node:16.18.0 AS build

#Set working directory
WORKDIR /app

#COPY package.json and package-lock.json
COPY server/package*.json ./

#Install dependencies
RUN npm install

#COPY source code
COPY server  .

#COPY prisma directory
COPY prisma ./prisma


#SET the port
EXPOSE 8000

#Npm run build
WORKDIR /app/prisma
RUN npx prisma generate

RUN npm run build

#Start the app
CMD ["npm", "start"]
