import { GalleryImage } from "../Types/Client";
import { Items } from "../Types/Items";

export const DUMMY_ITEM: Items[] = [
  {
    id: "1",
    name: "Man Cloth",
    category: "Shirt",
    color: "white",
    stock: 50,
    size: 105,
    descritption: "This is a PillaBerry MantoMan Cloth!",
    img: "https://source.unsplash.com/random/20",
    url: "https://www.naver.com",
  },
  {
    id: "2",
    name: "Woman Cloth",
    category: "T-Shirt",
    color: "gray",
    stock: 70,
    size: 90,
    descritption: "This is a PillaBerry Cloth for Woman!",
    img: "https://source.unsplash.com/random/21",
    url: "https://www.naver.com",
  },
  {
    id: "3",
    name: "Cool Accessory",
    category: "Accessory",
    color: "silver",
    stock: 70,
    size: "Free",
    descritption: "This is a PillaBerry Shinny Accessory!",
    img: "https://source.unsplash.com/random/22",
    url: "https://www.naver.com",
  },
  {
    id: "4",
    name: "Man Cloth",
    category: "Shirt",
    color: "white",
    stock: 50,
    size: 105,
    descritption: "This is a PillaBerry MantoMan Cloth!",
    img: "https://source.unsplash.com/random/?man",
    url: "https://www.naver.com",
  },
  {
    id: "5",
    name: "Woman Cloth",
    category: "T-Shirt",
    color: "gray",
    stock: 70,
    size: 90,
    descritption: "This is a PillaBerry Cloth for Woman!",
    img: "https://source.unsplash.com/random/?girl",
    url: "https://www.naver.com",
  },
  {
    id: "6",
    name: "Cool Accessory",
    category: "Accessory",
    color: "silver",
    stock: 70,
    size: "Free",
    descritption: "This is a PillaBerry Shinny Accessory!",
    img: "https://source.unsplash.com/random/?ring",
    url: "https://www.naver.com",
  },
  {
    id: "7",
    name: "Man Cloth",
    category: "Shirt",
    color: "white",
    stock: 50,
    size: 105,
    descritption: "This is a PillaBerry MantoMan Cloth!",
    img: "https://source.unsplash.com/random/?boy",
    url: "https://www.naver.com",
  },
  {
    id: "8",
    name: "Woman Cloth",
    category: "T-Shirt",
    color: "gray",
    stock: 70,
    size: 90,
    descritption: "This is a PillaBerry Cloth for Woman!",
    img: "https://source.unsplash.com/random/?women",
    url: "https://www.naver.com",
  },
  {
    id: "9",
    name: "Cool Accessory",
    category: "Accessory",
    color: "silver",
    stock: 70,
    size: "Free",
    descritption: "This is a PillaBerry Shinny Accessory!",
    img: "https://source.unsplash.com/random/?necklace",
    url: "https://www.naver.com",
  },
];

export const DUMMY_GALLERY_IMAGE: GalleryImage[] = [
  {
    id: "no1",
    imageUrl: "https://source.unsplash.com/random/1",
    caption: "이미지설명",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-01"),
    user: {
      id: "no1",
      username: "no1",
      profileImageUrl: "https://source.unsplash.com/random/1",
    },
    tags: ["tag1", "tag2"],
  },
  {
    id: "no2",
    imageUrl: "https://source.unsplash.com/random/2",
    caption: "두 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-02"),
    user: {
      id: "no2",
      username: "no2",
      profileImageUrl: "https://source.unsplash.com/random/2",
    },
    tags: ["tag3", "tag4"],
  },
  {
    id: "no3",
    imageUrl: "https://source.unsplash.com/random/3",
    caption: "세 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-03"),
    user: {
      id: "no3",
      username: "no3",
      profileImageUrl: "https://source.unsplash.com/random/3",
    },
    tags: ["tag5", "tag6"],
  },
  {
    id: "no4",
    imageUrl: "https://source.unsplash.com/random/4",
    caption: "네 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-04"),
    user: {
      id: "no4",
      username: "no4",
      profileImageUrl: "https://source.unsplash.com/random/4",
    },
    tags: ["tag7", "tag8"],
  },
  {
    id: "no5",
    imageUrl: "https://source.unsplash.com/random/5",
    caption: "다섯 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-05"),
    user: {
      id: "no5",
      username: "no5",
      profileImageUrl: "https://source.unsplash.com/random/5",
    },
    tags: ["tag9", "tag10"],
  },
  {
    id: "no6",
    imageUrl: "https://source.unsplash.com/random/6",
    caption: "여섯 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-06"),
    user: {
      id: "no6",
      username: "no6",
      profileImageUrl: "https://source.unsplash.com/random/6",
    },
    tags: ["tag11", "tag12"],
  },
  {
    id: "no7",
    imageUrl: "https://source.unsplash.com/random/7",
    caption: "일곱 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-07"),
    user: {
      id: "no7",
      username: "no7",
      profileImageUrl: "https://source.unsplash.com/random/7",
    },
    tags: ["tag13", "tag14"],
  },
  {
    id: "no8",
    imageUrl: "https://source.unsplash.com/random/8",
    caption: "여덟 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-08"),
    user: {
      id: "no8",
      username: "no8",
      profileImageUrl: "https://source.unsplash.com/random/8",
    },
    tags: ["tag15", "tag16"],
  },
  {
    id: "no9",
    imageUrl: "https://source.unsplash.com/random/9",
    caption: "아홉 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-09"),
    user: {
      id: "no9",
      username: "no9",
      profileImageUrl: "https://source.unsplash.com/random/9",
    },
    tags: ["tag17", "tag18"],
  },
  {
    id: "no10",
    imageUrl: "https://source.unsplash.com/random/10",
    caption: "열 번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-10"),
    user: {
      id: "no10",
      username: "no10",
      profileImageUrl: "https://source.unsplash.com/random/10",
    },
    tags: ["tag19", "tag20"],
  },
  {
    id: "no11",
    imageUrl: "https://source.unsplash.com/random/11",
    caption: "열 한번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-11"),
    user: {
      id: "no11",
      username: "no11",
      profileImageUrl: "https://source.unsplash.com/random/11",
    },
    tags: ["tag21", "tag22"],
  },
  {
    id: "no12",
    imageUrl: "https://source.unsplash.com/random/12",
    caption: "열 두번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-12"),
    user: {
      id: "no12",
      username: "no12",
      profileImageUrl: "https://source.unsplash.com/random/12",
    },
    tags: ["tag23", "tag24"],
  },
  {
    id: "no13",
    imageUrl: "https://source.unsplash.com/random/13",
    caption: "열 세번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-13"),
    user: {
      id: "no13",
      username: "no13",
      profileImageUrl: "https://source.unsplash.com/random/13",
    },
    tags: ["tag25", "tag26"],
  },
  {
    id: "no14",
    imageUrl: "https://source.unsplash.com/random/14",
    caption: "열 한번째 이미지",
    likes: 0,
    comments: 0,
    timestamp: new Date("2021-09-14"),
    user: {
      id: "no14",
      username: "no14",
      profileImageUrl: "https://source.unsplash.com/random/14",
    },
    tags: ["tag27", "tag28"],
  },
  // {
  //   작가사진: "https://source.unsplash.com/random/14",
  //   이미지설명: "열 한번째 이미지",
  //     작가정보: {
  //     고유작가번호: "no14",
  //     username: "세계 전",
  //   },
  // },
];
